
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hendg
 */
public class CadastrarCarroGUI extends javax.swing.JFrame {

    ImageIcon carro01 = new javax.swing.ImageIcon(getClass().getResource("/Gol Quadrado.jpeg"));
    ImageIcon carro02 = new javax.swing.ImageIcon(getClass().getResource("/Fusca Azul.jpeg"));
    ImageIcon carro03 = new javax.swing.ImageIcon(getClass().getResource("/Delrey Creme.jpeg"));
    ImageIcon carro04 = new javax.swing.ImageIcon(getClass().getResource("/Galinha Cangaceira(1).png"));
    ImageIcon carro05 = new javax.swing.ImageIcon(getClass().getResource("/Batata_Inglesa-removebg-preview.png"));
    ImageIcon carro06 = new javax.swing.ImageIcon(getClass().getResource("/Foguete Spacex(1).jpg"));
    ImageIcon carro07 = new javax.swing.ImageIcon(getClass().getResource("/BMW Isetta(1).jpg"));
    ImageIcon carro08 = new javax.swing.ImageIcon(getClass().getResource("/Javali(1).jpg"));

    /**
     * Creates new form CadastrarCarroGUI
     */
    public CadastrarCarroGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        listarVeiculo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtListar = new javax.swing.JTable();
        jbLimpar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfModelo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbAlterar = new javax.swing.JButton();
        jbCadastrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfAno = new javax.swing.JTextField();
        jtfPlaca = new javax.swing.JTextField();
        jtfLugares = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfCor = new javax.swing.JTextField();
        jtfCod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jlCarros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtListar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Veiculo", "Modelo", "Ano", "Placa", "Cor", "Lugares"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListar);

        jbLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modelo");

        jtfModelo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfModelo.setText("BMW Isetta");
        jtfModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfModeloActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE CARRO");

        jbAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ano");

        jtfAno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfAno.setText("1957");

        jtfPlaca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfPlaca.setText("1S3TT4");

        jtfLugares.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfLugares.setText("2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cor");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Lugares");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Placa");

        jtfCor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfCor.setText("Vermelha");

        jtfCod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfCod.setText("7");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Cod.");

        jlCarros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfCor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfLugares, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfPlaca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlCarros)
                        .addGap(50, 50, 50)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlCarros))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCod, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(591, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListarMouseClicked
        // TODO add your handling code here:
        jtfCod.setText(jtListar.getValueAt(jtListar.getSelectedRow(), 0).toString());
        jtfModelo.setText(jtListar.getValueAt(jtListar.getSelectedRow(), 1).toString());
        jtfAno.setText(jtListar.getValueAt(jtListar.getSelectedRow(), 2).toString());
        jtfPlaca.setText(jtListar.getValueAt(jtListar.getSelectedRow(), 3).toString());
        jtfCor.setText(jtListar.getValueAt(jtListar.getSelectedRow(), 4).toString());
        jtfLugares.setText(jtListar.getValueAt(jtListar.getSelectedRow(), 5).toString());

        String c = jtfCod.getText();
        switch (c) {
            case "1":
                jlCarros.setIcon(carro01);
                break;
            case "2":
                jlCarros.setIcon(carro02);
                break;
            case "3":
                jlCarros.setIcon(carro03);
                break;
            case "4":
                jlCarros.setIcon(carro04);
                break;
            case "5":
                jlCarros.setIcon(carro05);
                break;
            case "6":
                jlCarros.setIcon(carro06);
                break;
            case "7":
                jlCarros.setIcon(carro07);
                break;
            case "8":
                jlCarros.setIcon(carro08);
                break;
        }
    }//GEN-LAST:event_jtListarMouseClicked

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        DAO dao = new DAO();
        if (dao.removeVeiculo(jtfModelo.getText())) {
            JOptionPane.showMessageDialog(null, "Veículo excluido com Sucesso!!!");
            listarVeiculo();
        } else {
            JOptionPane.showMessageDialog(null, "Veículo não foi localizado!");
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        if ((jtfCod.getText().equals("")) || (jtfModelo.getText().equals("")) || (jtfAno.getText().equals("")) || (jtfPlaca.getText().equals("")) || (jtfCor.getText().equals("")) || (jtfLugares.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!");
        } else {
            String modelo = jtfModelo.getText();
            int ano = Integer.parseInt(jtfAno.getText());
            String placa = jtfPlaca.getText();
            String cor = jtfCor.getText();
            String lugar = jtfLugares.getText();
            int cod = Integer.parseInt(jtfCod.getText());

            int r = JOptionPane.showConfirmDialog(null, "Confira e confirme se os dados estão corretos:"
                    + "\nCódigo: " + cod
                    + "\nModelo: " + modelo
                    + "\nAno: " + ano
                    + "\nPlaca: " + placa
                    + "\nCor: " + cor
                    + "\nLugares: " + lugar, "Confirmação", 0, 1);
            if (r == 0) {
                Veiculo veiculo = new Veiculo();
                veiculo.setCod(cod);
                veiculo.setModelo(modelo);
                veiculo.setAno(ano);
                veiculo.setPlaca(placa);
                veiculo.setCor(cor);
                veiculo.setLugar(lugar);
                DAO dao = new DAO();
                if (dao.alterarVeiculo(veiculo, cod)) {
                    JOptionPane.showMessageDialog(null, "Cadastro alterado com Sucesso!!!");
                    listarVeiculo();
                } else {
                    JOptionPane.showMessageDialog(null, "O Cadastro não pode ser Alterado!!!");
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
        if ((jtfCod.getText().equals("")) || (jtfModelo.getText().equals("")) || (jtfAno.getText().equals("")) || (jtfPlaca.getText().equals("")) || (jtfCor.getText().equals("")) || (jtfLugares.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!");
        } else {
            int cod = Integer.parseInt(jtfCod.getText());
            String modelo = jtfModelo.getText();
            int ano = Integer.parseInt(jtfAno.getText());
            String placa = jtfPlaca.getText();
            String cor = jtfCor.getText();
            String lugar = jtfLugares.getText();

            int r = JOptionPane.showConfirmDialog(null, "Confira e confirme se os dados estão corretos:"
                    + "\nCódigo: " + cod
                    + "\nModelo: " + modelo
                    + "\nAno: " + ano
                    + "\nPlaca: " + placa
                    + "\nCor: " + cor
                    + "\nLugares: " + lugar, "Confirmação", 0, 1);
            if (r == 0) {
                Veiculo veiculo = new Veiculo();
                veiculo.setCod(cod);
                veiculo.setModelo(modelo);
                veiculo.setAno(ano);
                veiculo.setPlaca(placa);
                veiculo.setCor(cor);
                veiculo.setLugar(lugar);
                DAO dao = new DAO();
                if (dao.incluirVeiculo(veiculo)) {
                    JOptionPane.showMessageDialog(null, "Veículo Cadastrado com Sucesso!!!");
                    listarVeiculo();
                } else {
                    JOptionPane.showMessageDialog(null, "Veículo não pode ser Cadastrado!!!");
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jtfModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfModeloActionPerformed

    public void listarVeiculo() {
        DAO dao = new DAO();
        ResultSet rs = dao.consultarNomeVeiculo();
        DefaultTableModel tabela = (DefaultTableModel) jtListar.getModel();

        while (tabela.getRowCount() > 0) {
            tabela.removeRow(0);
        }
        Object dados[] = new Object[6];
        try {
            while (rs.next()) {
                for (int i = 0; i < 6; i++) {
                    dados[i] = rs.getString(i + 1);
                }
                tabela.addRow(dados);
            }
            dao.encerraConexao();
        } catch (SQLException ex) {
            Logger.getLogger(CadastrarCarroGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCarroGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlCarros;
    private javax.swing.JTable jtListar;
    private javax.swing.JTextField jtfAno;
    private javax.swing.JTextField jtfCod;
    private javax.swing.JTextField jtfCor;
    private javax.swing.JTextField jtfLugares;
    private javax.swing.JTextField jtfModelo;
    private javax.swing.JTextField jtfPlaca;
    // End of variables declaration//GEN-END:variables
}
